# ⚡ Electric Vehicle Population Data 

> **Dataset:** Electric Vehicle Population Data (Washington State, USA)  
> **Total Records:** 1,50,487 | **Features:** 17  
> **Goal:** Understand EV adoption trends, market share, range distribution, and geographic spread.

---

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Electric_Vehicle_Population_Data_RAW.csv")
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,KM8K33AGXL,King,Seattle,WA,98103.0,2020,HYUNDAI,KONA,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,258,0,43.0,249675142,POINT (-122.34301 47.659185),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303300e+10
1,1C4RJYB61N,King,Bothell,WA,98011.0,2022,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,1.0,233928502,POINT (-122.20578 47.762405),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
2,1C4RJYD61P,Yakima,Yakima,WA,98908.0,2023,JEEP,GRAND CHEROKEE,Plug-in Hybrid Electric Vehicle (PHEV),Not eligible due to low battery range,25,0,14.0,229675939,POINT (-120.6027202 46.5965625),PACIFICORP,5.307700e+10
3,5YJ3E1EA7J,King,Kirkland,WA,98034.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215,0,45.0,104714466,POINT (-122.209285 47.71124),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
4,WBY7Z8C5XJ,Thurston,Olympia,WA,98501.0,2018,BMW,I3,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,97,0,22.0,185498386,POINT (-122.89692 47.043535),PUGET SOUND ENERGY INC,5.306701e+10

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150494 entries, 0 to 150493
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         150494 non-null  str
 1   County                                             150491 non-null  str
 2   City                                               150491 non-null  str
 3   State                                              150494 non-null  str
 4   Postal Code                                        150491 non-null  float64
 5   Model Year                                         150494 non-null  int64
 6   Make                                               150494 non-null  str
 7   Model                                              150494 non-null  str
 8   Electric Vehicle Type                              150494 non-null  str
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  150494 non-null  str
 10  Electric Range                                     150494 non-null  int64
 11  Base MSRP                                          150494 non-null  int64
 12  Legislative District                               150153 non-null  float64
 13  DOL Vehicle ID                                     150494 non-null  int64
 14  Vehicle Location                                   150487 non-null  str
 15  Electric Utility                                   150491 non-null  str
 16  2020 Census Tract                                  150491 non-null  float64
dtypes: float64(3), int64(4), str(10)
memory usage: 19.5 MB

In [4]:
df.describe()

,Postal Code,Model Year,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,2020 Census Tract
count,150491.000000,150494.000000,150494.000000,150494.000000,150153.000000,1.504940e+05,1.504910e+05
mean,98168.343476,2020.005548,67.874613,1312.540068,29.344648,2.111116e+08,5.297196e+10
std,2473.514359,3.015167,96.227649,9230.949606,14.824850,8.196162e+07,1.638776e+09
min,1730.000000,1997.000000,0.000000,0.000000,1.000000,4.385000e+03,1.081042e+09
25%,98052.000000,2018.000000,0.000000,0.000000,18.000000,1.693448e+08,5.303301e+10
50%,98122.000000,2021.000000,18.000000,0.000000,33.000000,2.150311e+08,5.303303e+10
75%,98370.000000,2023.000000,97.000000,0.000000,43.000000,2.399122e+08,5.305307e+10
max,99577.000000,2024.000000,337.000000,845000.000000,49.000000,4.792548e+08,5.603300e+10

In [5]:
df.isnull().sum()

VIN (1-10)                                             0
County                                                 3
City                                                   3
State                                                  0
Postal Code                                            3
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         0
Base MSRP                                              0
Legislative District                                 341
DOL Vehicle ID                                         0
Vehicle Location                                       7
Electric Utility                                       3
2020 Census Tract                                      3
dtype: int64

In [6]:
df.dtypes

VIN (1-10)                                               str
County                                                   str
City                                                     str
State                                                    str
Postal Code                                          float64
Model Year                                             int64
Make                                                     str
Model                                                    str
Electric Vehicle Type                                    str
Clean Alternative Fuel Vehicle (CAFV) Eligibility        str
Electric Range                                         int64
Base MSRP                                              int64
Legislative District                                 float64
DOL Vehicle ID                                         int64
Vehicle Location                                         str
Electric Utility                                         str
2020 Census Tract                                    float64
dtype: object

In [7]:
df.isnull().sum()/(len(df)*100) # used to check percentange

VIN (1-10)                                           0.000000e+00
County                                               1.993435e-07
City                                                 1.993435e-07
State                                                0.000000e+00
Postal Code                                          1.993435e-07
Model Year                                           0.000000e+00
Make                                                 0.000000e+00
Model                                                0.000000e+00
Electric Vehicle Type                                0.000000e+00
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0.000000e+00
Electric Range                                       0.000000e+00
Base MSRP                                            0.000000e+00
Legislative District                                 2.265871e-05
DOL Vehicle ID                                       0.000000e+00
Vehicle Location                                     4.651348e-07
Electric Utility                                     1.993435e-07
2020 Census Tract                                    1.993435e-07
dtype: float64

In [8]:
df.dropna().shape

(150149, 17)

In [9]:
df['Legislative District']=df['Legislative District'].fillna(df['Legislative District'].mode().iloc[0])

In [10]:
df=df.dropna()

In [11]:
df.info()

<class 'pandas.DataFrame'>
Index: 150487 entries, 0 to 150493
Data columns (total 17 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         150487 non-null  str
 1   County                                             150487 non-null  str
 2   City                                               150487 non-null  str
 3   State                                              150487 non-null  str
 4   Postal Code                                        150487 non-null  float64
 5   Model Year                                         150487 non-null  int64
 6   Make                                               150487 non-null  str
 7   Model                                              150487 non-null  str
 8   Electric Vehicle Type                              150487 non-null  str
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  150487 non-null  str
 10  Electric Range                                     150487 non-null  int64
 11  Base MSRP                                          150487 non-null  int64
 12  Legislative District                               150487 non-null  float64
 13  DOL Vehicle ID                                     150487 non-null  int64
 14  Vehicle Location                                   150487 non-null  str
 15  Electric Utility                                   150487 non-null  str
 16  2020 Census Tract                                  150487 non-null  float64
dtypes: float64(3), int64(4), str(10)
memory usage: 20.7 MB

In [12]:
df.isnull().sum()

VIN (1-10)                                           0
County                                               0
City                                                 0
State                                                0
Postal Code                                          0
Model Year                                           0
Make                                                 0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       0
Base MSRP                                            0
Legislative District                                 0
DOL Vehicle ID                                       0
Vehicle Location                                     0
Electric Utility                                     0
2020 Census Tract                                    0
dtype: int64

In [13]:
col=df.columns
for i in col:
    print(i)
    print(df[i].unique())

VIN (1-10)
<StringArray>
['KM8K33AGXL', '1C4RJYB61N', '1C4RJYD61P', '5YJ3E1EA7J', 'WBY7Z8C5XJ',
 '5YJ3E1EAXL', '2C4RC1N77H', '5YJYGDEE3L', '5YJ3E1EA1J', '7SAYGDEF0P',
 ...
 '7JRBR0FZ7M', '4JGDA6DBXH', '1FTZR081XY', '50EA1DCA2N', 'WB533CF03R',
 '1FMCU0EZ8M', '7FCTGAAL0P', 'WA1CAAGE9R', 'WA1G2BFZ5N', 'JN1CF0BB5P']
Length: 9528, dtype: str
County
<StringArray>
[       'King',      'Yakima',    'Thurston',   'Snohomish',      'Island',
      'Kitsap',     'Whitman',      'Skagit',    'Kittitas', 'Walla Walla',
 ...
    'Kootenai',  'Williamson',       'Sarpy',  'Las Animas',   'St. Clair',
    'Hennepin',        'Maui',        'Bell',  'Portsmouth',     'Suffolk']
Length: 183, dtype: str
City
<StringArray>
[      'Seattle',       'Bothell',        'Yakima',      'Kirkland',
       'Olympia',    'Marysville',          'Kent',   'Woodinville',
    'Coupeville',      'Bellevue',
 ...
       'Alameda',       'Prosper',       'Killeen',         'Tampa',
     'Camarillo',      'Coronado',       'Suffolk',    'Middletown',
     'Ewa Beach', 'Ellicott City']
Length: 683, dtype: str
State
<StringArray>
['WA', 'CA', 'IL', 'NE', 'MO', 'AZ', 'VA', 'KY', 'NC', 'MD', 'DC', 'WY', 'GA',
 'OR', 'FL', 'MS', 'TX', 'AL', 'HI', 'CO', 'CT', 'LA', 'MT', 'NV', 'NY', 'NJ',
 'OH', 'DE', 'PA', 'IN', 'NH', 'AR', 'ID', 'UT', 'SC', 'KS', 'AK', 'MA', 'MN']
Length: 39, dtype: str
Postal Code
[98103. 98011. 98908. 98034. 98501. 98271. 98042. 98072. 98239. 98004.
 98033. 98367. 98366. 98275. 98052. 98579. 98112. 98125. 98311. 98370.
 98312. 98108. 98258. 98383. 98346. 98506. 98022. 98109. 98006. 98133.
 98002. 98936. 98947. 98057. 98008. 98188. 98392. 98277. 98012. 98177.
 98380. 98058. 98272. 98110. 98155. 98597. 98028. 98502. 98168. 98292.
 98056. 98039. 98122. 98021. 98296. 98948. 98144. 98204. 98036. 98029.
 98310. 98107. 98117. 98092. 98007. 98503. 98903. 98942. 98199. 98146.
 98105. 98101. 98902. 98516. 98513. 98512. 98115. 98020. 98340. 98119.
 98178. 98026. 98589. 98074. 98031. 98270. 99163. 98576. 98273. 98922.
 98059. 98233. 98208. 98166. 98221. 98102. 98121. 98257. 99362. 99205.
 98087. 98005. 98274. 98203. 98237. 98901. 98037. 98249. 98826. 98148.
 98801. 98837. 99207. 99115. 98284. 98116. 98232. 98926. 98315. 98055.
 98198. 99167. 99109. 98043. 98236. 98070. 98201. 98943. 98260. 98815.
 98822. 98683. 98030. 98252. 99114. 98682. 98858. 98629. 98498. 98606.
 98368. 98662. 98045. 98685. 98686. 98674. 98359. 98106. 98382. 98047.
 98603. 98001. 98632. 99026. 98104. 98075. 98027. 98320. 98625. 98671.
 98663. 98607. 98023. 98019. 98604. 98684. 98660. 98365. 98223. 98664.
 98467. 98337. 98040. 98661. 98645. 98003. 98626. 98642. 98290. 98407.
 98053. 98409. 98388. 98439. 98665. 99004. 99354. 99223. 98349. 98024.
 98944. 98134. 98466. 98611. 98532. 98937. 99212. 98672. 98930. 98569.
 98675. 98601. 98376. 98371. 98520. 98390. 98531. 98241. 99336. 98358.
 98605. 98374. 98335. 99403. 98354. 98051. 98282. 98391. 98250. 98362.
 98342. 98329. 98225. 98932. 98038. 99301. 98226. 98294. 98333. 98339.
 98404. 98363. 98345. 98823. 99027. 98332. 98405. 99006. 99037. 98032.
 98841. 98584. 98433. 98014. 98635. 98935. 98951. 98953. 99201. 98406.
 98526. 99208. 98262. 98499. 98136. 98331. 98244. 98248. 98065. 98338.
 98530. 98010. 98126. 98251. 98325. 98649. 98938. 98118. 98923. 98620.
 98077. 98288. 98253. 98528. 99202. 98229. 99352. 99349. 99216. 99019.
 98580. 98833. 99338. 98264. 98445. 98856. 98862. 98816. 98857. 98638.
 98631. 98802. 98444. 99218. 99030. 98596. 98373. 99025. 98360. 99344.
 98261. 98372. 99206. 98640. 98235. 98321. 98844. 99224. 98357. 99353.
 99156. 98303. 99016. 98831. 99328. 98612. 99203. 98245. 98403. 98524.
 99204. 99023. 98934. 98644. 98446. 98355. 98328. 98843. 99217. 99323.
 98563. 98402. 98408. 99022. 98624. 99130. 98651. 99021. 98230. 99337.
 99125. 99356. 98610. 98591. 98327. 94901. 98848. 98387. 99005. 98394.
 99324. 98068. 98304. 98950. 98592. 99326. 98279. 98847. 98465. 98617.
 99350. 98550. 98593. 99161. 98401. 98385. 98164. 99341. 98256. 99169.
 98422. 98577. 98639. 98564. 99036. 98855. 98361. 99357. 98266. 98849.
 98925. 98424. 98537. 99402. 98546. 98828. 99029. 98356. 98421. 98541.
 98281. 98547. 60048. 98585. 98812. 99003. 98542. 99001. 68135. 98375.
 99170. 98595. 98247. 98648. 98650. 98834. 92131. 98850. 98326. 99141.
 99009. 98557. 98418. 99134. 99343. 99123. 98588. 98940. 64079. 99126.
 93555. 99320. 60035. 98283. 99008. 98548. 98941. 85281. 98555. 99011.
 98438. 98570. 23238. 90621. 99330. 98568. 40026. 98314. 98276. 98840.
 99113. 98571. 28376. 99111. 98587. 98344. 98297. 98673. 98538. 99119.
 98533. 98286. 21401. 98582. 98295. 21701. 99361. 20003. 68102. 99185.
 82001. 90249. 99139. 98814. 99017. 94565. 99031. 98323. 30030. 99122.
 62281. 98224. 98586. 99166. 98240. 98443. 92058. 99180. 99360. 98158.
 97214. 98851. 22554. 34242. 98206. 99347. 99148. 99173. 20732. 98846.
 99155. 98619. 98377. 98641. 92102. 98535. 39531. 92057. 92277. 78251.
 99121. 21157. 92595. 99159. 99181. 98590. 98572. 36877. 98336. 99147.
 99018. 96740. 94303. 78412. 99138. 99137. 93245. 98830. 99013. 28305.
 98381. 99118. 98220. 92106. 20002. 98845. 99116. 33547. 79911. 95051.
 99033. 80925. 93436. 92585. 98614.  6443. 71446. 23321. 97304. 99110.
 64084. 76310. 59106. 98267. 99133. 96752. 22151. 28390. 31088. 85086.
 95833. 95062. 98243. 98946. 20105. 21037. 92620. 98050. 75244. 98263.
 89029. 12833. 95014. 98832. 99039. 92154.  8641. 98613. 23185. 61201.
 89138. 45243. 19901. 22180. 80919. 97756. 30013. 96734. 99135. 93041.
 60077. 99101. 20007. 23455. 19131. 98616. 21113. 78254.  6355. 21012.
 92103. 22304. 46342. 98670. 79927. 98396. 98305. 20744.  6371. 98583.
 98643. 85248. 94707. 98565. 20906. 98351. 20653. 28545. 92101. 92124.
 22308. 20774. 23518. 90620. 98536. 30024.  3804. 98647. 23508. 21040.
 98621. 99179. 99129. 60605. 98562. 82801. 95688. 99117. 98527. 13638.
 70461. 17050. 90802. 20878. 98952. 28387. 12401. 28312. 95476. 33131.
 92056. 92308. 95054. 99032. 92114. 32792.  8048. 27958. 95131. 94710.
 96818. 78121. 98504. 91913. 85250. 90064. 76092. 22903. 23602. 98330.
 94559. 95112. 80547. 20637.  7302. 94043. 72207. 86351. 95661. 92201.
 90005. 76528. 20762. 63137. 92647. 42701. 93940. 35124. 83648. 60004.
 98507. 10308. 60527. 98124. 98853. 92672. 99171.  8055. 97330.  7003.
 40121. 23456. 21036.  8202. 97367. 70037. 84121. 92703. 33326. 94535.
 60201. 98227. 29486. 66043. 95401. 23150. 29909. 22405. 98813. 20895.
 29483.  6379. 78233. 97703. 22307. 20171. 29404. 36619. 23503. 99346.
 32506. 92660. 99577. 89166. 77539. 99143. 13603. 27332. 21756. 20854.
 97404. 20603. 99140. 75026. 61822. 95120. 20879. 80019. 23462. 33487.
 80504. 98280. 46802. 80923. 99131. 95817. 90016. 98575. 92130. 34108.
 80111.  6385.  1824. 21076. 22015. 94510. 89129. 91801.  8033. 90713.
 92310. 95377. 89118. 98411. 23464. 78748. 80501. 20755. 85212. 92109.
 94556. 89135. 92618. 98821.  1730. 20814. 92051. 27205. 67218. 94536.
 99034. 93560. 84115. 91915. 83876. 78681. 68123. 30905. 99371. 27516.
 20024. 81082. 62220. 12866. 55408. 75074.  7103. 21054. 93001. 98255.
 85040. 20815. 96753. 85395.  1731. 93955. 97477. 94501. 75078. 76542.
 95135. 33621. 78414. 93010. 92107. 92118. 95828. 23707. 23435. 21769.
 96706. 21042.]
Model Year
[2020 2022 2023 2018 2017 2016 2019 2013 2015 2014 2021 2011 2012 2024
 2010 2008 2002 2000 1998 2003 1999 1997]
Make
<StringArray>
[             'HYUNDAI',                 'JEEP',                'TESLA',
                  'BMW',             'CHRYSLER',                 'FORD',
               'TOYOTA',                 'AUDI',               'NISSAN',
                  'KIA',            'CHEVROLET',           'VOLKSWAGEN',
                 'FIAT',                 'MINI',                'SMART',
               'RIVIAN',                'VOLVO',              'PORSCHE',
                'HONDA',           'MITSUBISHI',               'SUBARU',
             'POLESTAR',        'MERCEDES-BENZ',             'CADILLAC',
               'JAGUAR',              'LINCOLN',              'GENESIS',
                'LUCID',                'LEXUS',               'FISKER',
                'MAZDA',           'LAND ROVER',                'TH!NK',
       'AZURE DYNAMICS',           'ALFA ROMEO', 'WHEEGO ELECTRIC CARS',
              'BENTLEY']
Length: 37, dtype: str
Model
<StringArray>
[          'KONA', 'GRAND CHEROKEE',        'MODEL 3',             'I3',
       'PACIFICA',        'MODEL Y',         'FUSION',    'PRIUS PRIME',
         'E-TRON',           'LEAF',
 ...
        'S-CLASS',         'RANGER',           'GV70',         'TONALE',
         'WHEEGO',            '918',    'FLYING SPUR',          '745LE',
    'S-10 PICKUP',       'BENTAYGA']
Length: 127, dtype: str
Electric Vehicle Type
<StringArray>
['Battery Electric Vehicle (BEV)', 'Plug-in Hybrid Electric Vehicle (PHEV)']
Length: 2, dtype: str
Clean Alternative Fuel Vehicle (CAFV) Eligibility
<StringArray>
[                     'Clean Alternative Fuel Vehicle Eligible',
                        'Not eligible due to low battery range',
 'Eligibility unknown as battery range has not been researched']
Length: 3, dtype: str
Electric Range
[258  25 215  97 266  33 291   0  19 220 204  84  26  13 249  38 103 322
 125 330 222 239  73 259  75  20 150  16  32  76  21 151 200  72 149 238
 289 208  34  53  30  81 110 210  22  58  17  18  87   6  93 308  14 107
 293  35  47  23 153  68 270  42 233  31 234  12  41 265  83  37  82  29
 203  10  40  24 114  39   8 126 218  15 124 337 111  27 192 245  28 170
  62 100  48  56  95   9  36  11  51  57  59  74]
Base MSRP
[     0  69900  31950  52900  32250  90700  54950  36900  59900  45600
  52650  39995  53400  64950  33950 102000  75095 110950  44100  81100
 184400  36800  43700  55700  34995  91250 109000  98950  89100  32995
 845000]
Legislative District
[43.  1. 14. 45. 22. 38. 47. 10. 48. 26. 21. 20. 46. 23. 39. 35. 11. 44.
 31. 41. 32. 15. 33.  2. 36. 37.  5. 34. 13.  9. 40. 16.  3. 12.  7. 18.
 17. 28. 24. 30. 19. 49. 27. 29.  6.  8.  4. 25. 42.]
DOL Vehicle ID
[249675142 233928502 229675939 ... 180705626 240473950 207667589]
Vehicle Location
<StringArray>
[   'POINT (-122.34301 47.659185)',    'POINT (-122.20578 47.762405)',
 'POINT (-120.6027202 46.5965625)',    'POINT (-122.209285 47.71124)',
    'POINT (-122.89692 47.043535)',   'POINT (-122.1713847 48.10433)',
    'POINT (-122.111625 47.36078)',    'POINT (-122.151665 47.75855)',
 'POINT (-122.6880708 48.2179983)',    'POINT (-122.201905 47.61385)',
 ...
      'POINT (-97.365265 27.6835)',    'POINT (-119.042975 34.22104)',
   'POINT (-117.245975 32.746635)',      'POINT (-117.1777 32.68979)',
 'POINT (-121.4242477 38.5024987)',     'POINT (-76.34389 36.829805)',
      'POINT (-76.42047 36.87704)',      'POINT (-77.54559 39.44235)',
    'POINT (-158.019325 21.33516)',     'POINT (-76.83207 39.276485)']
Length: 822, dtype: str
Electric Utility
<StringArray>
[                                                                    'CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA)',
                                                                    'PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA)',
                                                                                                       'PACIFICORP',
                                                                                           'PUGET SOUND ENERGY INC',
                                                                                                      'AVISTA CORP',
                                                                                'NO KNOWN ELECTRIC UTILITY SERVICE',
                                                                                    'MODERN ELECTRIC WATER COMPANY',
                                                                                        'PUD NO 1 OF CHELAN COUNTY',
                                                                                         'PUD NO 2 OF GRANT COUNTY',
                                                 'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLARK COUNTY - (WA)',
                                                                                       'PUD NO 1 OF DOUGLAS COUNTY',
                                  'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY',
                            'BONNEVILLE POWER ADMINISTRATION||PUGET SOUND ENERGY INC||PUD NO 1 OF JEFFERSON COUNTY',
                                                      'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF COWLITZ COUNTY',
                           'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF MASON COUNTY|PUD NO 1 OF JEFFERSON COUNTY',
                                                      'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF CLALLAM COUNTY',
                                     'BONNEVILLE POWER ADMINISTRATION||PACIFICORP||PUD NO 1 OF CLARK COUNTY - (WA)',
               'BONNEVILLE POWER ADMINISTRATION||TOWN OF STEILACOOM|CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY',
                                       'BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||INLAND POWER & LIGHT COMPANY',
                                                         'BONNEVILLE POWER ADMINISTRATION||CITY OF RICHLAND - (WA)',
                                                                      'CITY OF TACOMA - (WA)||TANNER ELECTRIC COOP',
                                          'BONNEVILLE POWER ADMINISTRATION||PACIFICORP||BENTON RURAL ELECTRIC ASSN',
                                                       'BONNEVILLE POWER ADMINISTRATION||PUD 1 OF SNOHOMISH COUNTY',
                                 'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PUD NO 1 OF LEWIS COUNTY',
                                                    'BONNEVILLE POWER ADMINISTRATION||VERA IRRIGATION DISTRICT #15',
                                                    'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF KLICKITAT COUNTY',
                                                 'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF GRAYS HARBOR COUNTY',
                                                       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF BENTON COUNTY',
                                          'BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||PUD NO 1 OF ASOTIN COUNTY',
                                     'BONNEVILLE POWER ADMINISTRATION||CITY OF MILTON - (WA)|CITY OF TACOMA - (WA)',
                                                        'BONNEVILLE POWER ADMINISTRATION||ORCAS POWER & LIGHT COOP',
                                                               'PUGET SOUND ENERGY INC||PUD NO 1 OF WHATCOM COUNTY',
                                                      'BONNEVILLE POWER ADMINISTRATION||BENTON RURAL ELECTRIC ASSN',
                                                     'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF FRANKLIN COUNTY',
                                                    'BONNEVILLE POWER ADMINISTRATION||INLAND POWER & LIGHT COMPANY',
                                                                                      'PUD NO 1 OF OKANOGAN COUNTY',
                                 'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PUD NO 3 OF MASON COUNTY',
                                                                                       'PUD NO 1 OF WHATCOM COUNTY',
           'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||LAKEVIEW LIGHT & POWER|PENINSULA LIGHT COMPANY',
                                                     'BONNEVILLE POWER ADMINISTRATION||CITY OF PORT ANGELES - (WA)',
                                                                                            'CITY OF TACOMA - (WA)',
                                                         'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF SKAMANIA CO',
                                                                                                 'CITY OF CHEWELAH',
                                                                                           'CITY OF SEATTLE - (WA)',
                                                       'BONNEVILLE POWER ADMINISTRATION||CITY OF ELLENSBURG - (WA)',
                                                                                   'OKANOGAN COUNTY ELEC COOP, INC',
   'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PARKLAND LIGHT & WATER COMPANY|PENINSULA LIGHT COMPANY',
                                                      'BONNEVILLE POWER ADMINISTRATION||PUD NO 2 OF PACIFIC COUNTY',
                                        'BONNEVILLE POWER ADMINISTRATION||AVISTA CORP||BIG BEND ELECTRIC COOP, INC',
                                                                                  'PUD NO 1 OF PEND OREILLE COUNTY',
                                                    'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF WAHKIAKUM COUNTY',
 'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||ELMHURST MUTUAL POWER & LIGHT CO|PENINSULA LIGHT COMPANY',
                                  'BONNEVILLE POWER ADMINISTRATION||CITY OF CENTRALIA - (WA)|CITY OF TACOMA - (WA)',
                                 'BONNEVILLE POWER ADMINISTRATION||TOWN OF EATONVILLE - (WA)|CITY OF TACOMA - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||ALDER MUTUAL LIGHT CO, INC|PENINSULA LIGHT COMPANY',
                                                   'BONNEVILLE POWER ADMINISTRATION||COLUMBIA RURAL ELEC ASSN, INC',
                                                                'CITY OF BLAINE - (WA)||PUD NO 1 OF WHATCOM COUNTY',
                                                                                            'CITY OF CHENEY - (WA)',
                                                                            'NON WASHINGTON STATE ELECTRIC UTILITY',
                                                     'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF KITTITAS COUNTY',
                                       'BONNEVILLE POWER ADMINISTRATION||PACIFICORP||COLUMBIA RURAL ELEC ASSN, INC',
                                 'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||PUD NO 1 OF MASON COUNTY',
                                                     'BONNEVILLE POWER ADMINISTRATION||BIG BEND ELECTRIC COOP, INC',
                                                                                     'PORTLAND GENERAL ELECTRIC CO',
   'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||OHOP MUTUAL LIGHT COMPANY, INC|PENINSULA LIGHT COMPANY',
                                                         'BONNEVILLE POWER ADMINISTRATION||CITY OF MCCLEARY - (WA)',
       'BONNEVILLE POWER ADMINISTRATION||CITY OF TACOMA - (WA)||BENTON RURAL ELECTRIC ASSN|PENINSULA LIGHT COMPANY',
                                                                 'CITY OF SUMAS - (WA)||PUD NO 1 OF WHATCOM COUNTY',
                                                         'BONNEVILLE POWER ADMINISTRATION||PENINSULA LIGHT COMPANY',
            'BONNEVILLE POWER ADMINISTRATION||TOWN OF RUSTON - (WA)|CITY OF TACOMA - (WA)||PENINSULA LIGHT COMPANY',
                                                       'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF ASOTIN COUNTY',
                                                        'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF FERRY COUNTY',
                                                  'BONNEVILLE POWER ADMINISTRATION||NESPELEM VALLEY ELEC COOP, INC',
                                                       'BONNEVILLE POWER ADMINISTRATION||CITY OF COULEE DAM - (WA)',
                                                    'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF JEFFERSON COUNTY',
                         'BONNEVILLE POWER ADMINISTRATION||PUD NO 1 OF ASOTIN COUNTY||INLAND POWER & LIGHT COMPANY']
Length: 76, dtype: str
2020 Census Tract
[5.30330048e+10 5.30330218e+10 5.30770029e+10 ... 2.40217526e+10
 1.50030084e+10 2.40276022e+10]

In [14]:
df[df.duplicated()].shape

(12, 17)

In [15]:
df=df.drop_duplicates()

In [16]:
df[df.duplicated()].shape

(0, 17)

In [17]:
df['State'].unique()

<StringArray>
['WA', 'CA', 'IL', 'NE', 'MO', 'AZ', 'VA', 'KY', 'NC', 'MD', 'DC', 'WY', 'GA',
 'OR', 'FL', 'MS', 'TX', 'AL', 'HI', 'CO', 'CT', 'LA', 'MT', 'NV', 'NY', 'NJ',
 'OH', 'DE', 'PA', 'IN', 'NH', 'AR', 'ID', 'UT', 'SC', 'KS', 'AK', 'MA', 'MN']
Length: 39, dtype: str

In [18]:
df.to_csv('Clean_EV_USA_WA_data.csv')